#!/bin/bash

NEWLINE=$'\n'
GENMESSAGE="--DO NOT EDIT THIS FILE! This file is generated by running the 'npm run build' command from this repos root. $NEWLINE"

build_browserify_command () {
  local PACKAGEPATH=$1
  local PACKAGENAME=$2
  local OUTPUTPATH=$3
  local SCHEMANAME=$4
  local VERSION=$5
  local URL=$6
  if [ -z "$7" ]; then
    local FLAGS=""
  else
    local FLAGS=$7
  fi

  local COMMAND="./node_modules/.bin/browserify $FLAGS -r $PACKAGEPATH:$PACKAGENAME"
  local BUNDLE=`$COMMAND`
  local SQL=`wrap_npm_install_sql "$SCHEMANAME" "$PACKAGENAME" "$VERSION" "$URL" "$BUNDLE"`
  echo "$SQL" > "$OUTPUTPATH"
}

wrap_npm_install_sql () {
  local SCHEMANAME=$1
  local PACKAGENAME=$2
  local VERSION=$3
  local URL=$4
  local CODE=$5

  local SELECT="SELECT nodejsshim.npm_install('$SCHEMANAME'::text, '$PACKAGENAME'::text, '$VERSION'::text, '$URL'::text, \$code_body\$ $NEWLINE"
  local SQL="$GENMESSAGE$SELECT$CODE $NEWLINE"
  local SQL="$SQL\$code_body\$::text); $NEWLINE"

  echo "$SQL"
}
